Fixes

diff --git a/29-emulator/tools/android-wait-for-emulator b/29-emulator/tools/android-wait-for-emulator
--- a/29-emulator/tools/android-wait-for-emulator
+++ b/29-emulator/tools/android-wait-for-emulator
@@ -10,14 +10,11 @@ timeout_in_sec=360
 
 until [[ "$bootanim" =~ "stopped" ]]; do
   bootanim=`adb -e shell getprop init.svc.bootanim 2>&1 &`
-  if [[ "$bootanim" =~ "device not found" || "$bootanim" =~ "device offline"
-    || "$bootanim" =~ "running" ]]; then
-    let "failcounter += 1"
-    echo "Waiting for emulator to start"
-    if [[ $failcounter -gt timeout_in_sec ]]; then
-      echo "Timeout ($timeout_in_sec seconds) reached; failed to start emulator"
-      exit 1
-    fi
+  let "failcounter += 1"
+  echo "Waiting for emulator to start ($bootanim)"
+  if [[ $failcounter -gt timeout_in_sec ]]; then
+    echo "Timeout ($timeout_in_sec seconds) reached; failed to start emulator"
+    exit 1
   fi
   sleep 1
 done
